# Generated by Django 5.2.5 on 2025-08-11 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mydjangoapi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RefreshToken',
        ),
    ]
